### PR TITLE
add good hacker

### PR DESCRIPTION
**Pull request by steveyiyo**
Add a Good Hacker to the index page.

image

### CODE REVIEW

**Comment by wdzeng** [comment]
LGTM💪

**Comment by Jimmy01240397** [comment]
LGTM 👍

**Comment by Vincent550102** [comment]
LGTM, I'll merge them later.

**Comment by thc1006** [comment]
LGTM

**Comment by jerryhsu066** [comment]
LGTM 🚀🚀🚀

**Comment by littlechintw** [comment]
LGTM

**Comment by yc97463** [comment]
LGTM 🚀💪🚀💪

**Pull request merged**
